CONFIG_MCUX_PRJSEG_module.board.suite=y
CONFIG_MCUX_COMPONENT_driver.clock=y
CONFIG_MCUX_COMPONENT_driver.inputmux_connections=y
CONFIG_MCUX_COMPONENT_driver.reset=y
CONFIG_MCUX_COMPONENT_device.CMSIS=y
CONFIG_MCUX_COMPONENT_device.system=y
CONFIG_MCUX_COMPONENT_device.startup=y
CONFIG_MCUX_COMPONENT_CMSIS_DSP_Include=y
CONFIG_MCUX_COMPONENT_CMSIS_DSP_Source=y
CONFIG_MCUX_COMPONENT_driver.common=y
CONFIG_MCUX_COMPONENT_driver.gpio=y
CONFIG_MCUX_COMPONENT_driver.lpflexcomm=y
CONFIG_MCUX_COMPONENT_driver.lpflexcomm_lpuart=y
CONFIG_MCUX_COMPONENT_driver.mcx_spc=y
CONFIG_MCUX_COMPONENT_driver.port=y
CONFIG_MCUX_COMPONENT_utility.assert_lite=y
CONFIG_MCUX_COMPONENT_utilities.misc_utilities=y
CONFIG_MCUX_COMPONENT_utility.str=y
CONFIG_MCUX_COMPONENT_utility.debug_console_lite=y
CONFIG_MCUX_COMPONENT_component.lpuart_adapter=y
